import type { User } from "@/types/user";

export const users: User[] = [
  {
    id: "12.114.517-1",
    name: "Rosa Cinthia Hidalgo Espinoza",
    address: "Eliodoro Yáñez 8773, Valparaíso, Región de Valparaíso",
    comuna: "Valparaíso",
    region: "Región de Valparaíso",
    birth: "1978-12-06",
    sexo: "Femenino",
    email: "constanzaaravena@example.com",
    phone: "+56 42 392 4963",
  },
  {
    id: "12.935.380-4",
    name: "Juan Valenzuela Jara",
    address: "Manuel Rodríguez 691, Santiago, Región Metropolitana",
    comuna: "Santiago",
    region: "Región Metropolitana",
    birth: "1987-09-06",
    sexo: "Femenino",
    email: "nunezrichard@example.org",
    phone: "+56 55 232 2456",
  },
  {
    id: "18.907.962-9",
    name: "Karen Nicole Domínguez Barraza",
    address: "María Sánchez 467, Viña del Mar, Región de Valparaíso",
    comuna: "Viña del Mar",
    region: "Región de Valparaíso",
    birth: "1966-03-31",
    sexo: "Masculino",
    email: "figueroabenjamin@example.net",
    phone: "+56 9 1324 2456",
  },
  {
    id: "8.123.365-5",
    name: "Francisca Araya Mora",
    address: "Los Palmitos 331, Providencia, Región Metropolitana",
    comuna: "Providencia",
    region: "Región Metropolitana",
    birth: "1982-04-18",
    sexo: "Masculino",
    email: "acortes@example.org",
    phone: "+56 9 6811 4595",
  },
  {
    id: "6.662.218-6",
    name: "Jordán Maldonado-Salamanca Olate",
    address: "Calle Los Piñones 74, Quilpué, Región de Valparaíso",
    comuna: "Quilpué",
    region: "Región de Valparaíso",
    birth: "2002-01-24",
    sexo: "Masculino",
    email: "figueroacristina@example.org",
    phone: "+56 2 2307 9860",
  },
  {
    id: "15.745.422-2",
    name: "Yesica Rayén Sepúlveda Sanhueza",
    address: "Los Alerces 93 Dpto. 05, Las Condes, Región Metropolitana",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    birth: "1976-05-20",
    sexo: "Femenino",
    email: "maira10@example.com",
    phone: "+56 51 232 7151",
  },
  {
    id: "22.906.294-7",
    name: "Vicente Tito Barrera Ramírez",
    address: "Ana Cruces 381, Valparaíso, Región de Valparaíso",
    comuna: "Valparaíso",
    region: "Región de Valparaíso",
    birth: "2002-10-29",
    sexo: "Femenino",
    email: "gallardofelipe@example.net",
    phone: "+56 9 6948 1216",
  },
  {
    id: "23.964.345-0",
    name: "Daniela Pérez",
    address: "Lorena González 275, Santiago, Región Metropolitana",
    comuna: "Santiago",
    region: "Región Metropolitana",
    birth: "1955-11-14",
    sexo: "Masculino",
    email: "gonzalezrosario@example.org",
    phone: "+56 800 110 082",
  },
  {
    id: "13.932.586-9",
    name: "Daniel Leoncio Briceño Aguilera",
    address: "Emilia Sánchez 186, Viña del Mar, Región de Valparaíso",
    comuna: "Viña del Mar",
    region: "Región de Valparaíso",
    birth: "2000-07-08",
    sexo: "Femenino",
    email: "giovannilagos@example.net",
    phone: "+56 2 2460 2696",
  },
  {
    id: "18.355.492-9",
    name: "Manuel Daniel Rojas Toledo",
    address: "Francisco Garrido 472 Of. 734, Providencia, Región Metropolitana",
    comuna: "Providencia",
    region: "Región Metropolitana",
    birth: "1954-05-02",
    sexo: "Femenino",
    email: "robertonavarro@example.org",
    phone: "+56 600 543 011",
  },
];
